# Generated by Django 4.2.3 on 2025-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("Online shopping", "Online shopping"),
                    ("Electronics", "Electronics"),
                    ("Clothes", "Clothes"),
                    ("Transport", "Transport"),
                    ("Health", "Health"),
                    ("Education", "Education"),
                    ("Housing", "Housing"),
                    ("Entertainment", "Entertainment"),
                    ("Travel", "Travel"),
                    ("Gifts & Donations", "Gifts & Donations"),
                    ("Groceries", "Groceries"),
                    ("Eat", "Eat"),
                    ("Drink & Coffee", "Drink & Coffee"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
